### Problem Statement
A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.

- Null H        : There is no significant difference in the diameter of the cutlet between two units. (μ1 = μ2)
- Alternarive H : There is significant difference in the diameter of the cutlet between two units.(μ1 != μ2)

- Two sample two tailed t-test is applied

In [2]:
import pandas as pd
import numpy as np

from scipy import stats
from scipy.stats import norm

In [8]:
cutlets = pd.read_csv('Cutlets.csv')
cutlets.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [4]:
cutlets.shape

(35, 2)

In [12]:
unit_A = cutlets['Unit A']                                                  #unit_A = pd.Series(cutlets.loc[:, 'Unit A'])
unit_A

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [13]:
unit_B = cutlets['Unit B']                                          
unit_B

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [16]:
t_val, p_val = stats.ttest_ind(unit_A, unit_B)
t_val, p_val

(0.7228688704678063, 0.4722394724599501)

In [17]:
# at 5% significance level 
if (p_val<0.05):
    print('we reject the null hypothesis.')
    print ('there is significatnt differnce in the diameter of the cutlet between two units. (μ1 != μ2)')

else:
    print('we do not reject the null hypothesis')
    print ('There is no significant difference in the diameter of the cutlet between two units. (μ1 = μ2)')

we do not reject the null hypothesis
There is no significant difference in the diameter of the cutlet between two units. (μ1 = μ2)


-------------------------------------------------------------------------------------------------------------------------------

### Problem Statement
A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch. Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.

In [3]:
#Load the dataset 
labtat = pd.read_csv('LabTAT.csv')
labtat.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

We will apply Anova Ftest ie Analysis of variance between more than 2 samples.

- Null H        : There is no significant difference in the average Turn Around Time (TAT) of reports. 
- Alternarive H : There is significant difference in the average Turn Around Time (TAT) of reports.

In [5]:
# Anova ftest statistics: stats.f_oneway(column-1,column-2,column-3,column-4)
stat, p_val = stats.f_oneway(labtat.iloc[:,0], labtat.iloc[:,1], labtat.iloc[:,2], labtat.iloc[:,3])
stat, p_val 

(118.70421654401437, 2.1156708949992414e-57)

In [6]:
# compare p value with α = 0.05 (at 5% significance level)
if (p_val<0.05):
    print('we reject the null hypothesis.')
    print ('There is significant difference in the average Turn Around Time (TAT) of reports')

else:
    print('we do not reject the null hypothesis')
    print ('There is no significant difference in the average Turn Around Time (TAT) of reports')

we reject the null hypothesis.
There is significant difference in the average Turn Around Time (TAT) of reports


Atleast one sample TAT population mean is different Thus there is variance or difference in average Turn Around Time (TAT) of reports of the laboratories on their preferred list.

------------------------------------------------------------------------------------------------------------------------------

### Problem Statement
Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

In [9]:
from scipy.stats import chi2_contingency

In [10]:
#import the data
buyer_ratio = pd.read_csv('BuyerRatio.csv')
buyer_ratio.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

we will use Chi2 contengency independence test. because we don't know the underlying distribution but want to test whether two (or more) groups have the same distribution.

- Null H        : Male-female buyer ratios are similar across regions. (Independence of categorical variables)
- Alternarive H : Male-female buyer ratios are not similar across regions.(Dependence of categorical variables)

In [13]:
observed = np.array([[50,142,131,70],[435,1523,1356,750]])

In [16]:
chi2, p_val, df, expected = chi2_contingency(observed)
chi2, p_val, df, expected

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [17]:
# compare p value with α = 0.05 (at 5% significance level)
if (p_val<0.05):
    print('we reject the null hypothesis.')
    print ('Male-female buyer ratios are not similar across regions')

else:
    print('we do not reject the null hypothesis')
    print ('Male-female buyer ratios are similar across regions')

we do not reject the null hypothesis
Male-female buyer ratios are similar across regions


-------------------------------------------------------------------------------------------------------------------------------

### Problem Statement
TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences


In [18]:
cust_ord_form = pd.read_csv('Costomer+OrderForm.csv')
cust_ord_form.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

we will use Chi2 contengency independence test. because we don't know the underlying distribution but want to test whether two (or more) groups have the same distribution.

- Null H        : Independence of categorical variables (customer order forms defective % does not varies by centre) 
- Alternarive H : Dependence of categorical variables (customer order forms defective % varies by centre) 

In [20]:
cust_ord_form.shape

(300, 4)

In [23]:
print(cust_ord_form.Phillippines.value_counts())
print(cust_ord_form.Indonesia.value_counts())
print(cust_ord_form.Malta.value_counts())
print(cust_ord_form.India.value_counts())

Error Free    271
Defective      29
Name: Phillippines, dtype: int64
Error Free    267
Defective      33
Name: Indonesia, dtype: int64
Error Free    269
Defective      31
Name: Malta, dtype: int64
Error Free    280
Defective      20
Name: India, dtype: int64


In [24]:
observed1 = np.array([[271,267,269,280],[29,33,31,20]])
observed1

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [25]:
chi2, p_val, df, expected = chi2_contingency(observed1)
chi2, p_val, df, expected

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [26]:
# compare p value with α = 0.05 (at 5% significance level)
if (p_val<0.05):
    print('we reject the null hypothesis.')
    print ('customer order forms defective % varies by centre')

else:
    print('we do not reject the null hypothesis')
    print ('customer order forms defective % does not varies by centre')

we do not reject the null hypothesis
customer order forms defective % does not varies by centre
